apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/violeta2002/ci_cd_lab@sha256:851ab24fa0c85f444b2e1312d71d2e455c1d017e985b56b89687b11de2eaf840
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
